# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Software Engineering Group
description:      'The <a href="https://heig-vd.ch/" target="_blank">HEIG-VD</a> software engineering group blog.'
url:              https://heigvd-software-engineering.github.io/
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Andrew Fong'
  url:            https://twitter.com/fongandrewc

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

collections:
  projects:
    output: true

permalink: pretty

pagination:
  enabled: true
  per_page: 5
  permalink: 'page:num/'
  title: ':title'
  sort_reverse: true